### ISSUE TITLE
It still saves MD5 hashes after enabling plugin

### ISSUE THREAD

**Issue by stugmi** [tommm/password-hash#1]
For every new users it saves both bcrypt and md5 hash, not sure if feature or bug. Either way, it sort of ruins the whole reason for using it.

**Comment by srexi** [comment]
Hey @stugmi I noticed the same thing, however I looked into the source code of the plugin.
It simply just makes a random string and does a md5 hash of that, so in case we disable the plugin the user HAS to reset his password :).

Source:
inc/plugin/functions.php line:88-90

The new password and salt has nothing to do with the actual password.

**Comment by stugmi** [comment]
Yeah I noticed that too, I forgot to come back here and mention it.
